'use strict';
// ===== CONSTANTS =====
const COLORS=['#c9a84c','#4a9b6f','#6b9ed4','#c23050','#9b5bc9','#d4884a','#50c9b0','#c9bf4a','#7060d0','#60c9a0','#d04878','#5090d4','#c07840','#48c060','#c05050','#7ac948'];
const MODELS=[
 {id:'openai-fast',name:'OpenAI Fast',provider:'pollinations',rec:true,desc:'Fastest — general chat and quick tasks'},
 {id:'openai',name:'OpenAI',provider:'pollinations',desc:'Balanced quality for most tasks'},
 {id:'openai-large',name:'OpenAI Large',provider:'pollinations',desc:'Powerful — complex reasoning and coding'},
 {id:'gemini-fast',name:'Gemini 2.5 Flash Lite',provider:'pollinations',desc:'Ultra-fast Google model'},
 {id:'gemini',name:'Gemini 3 Flash',provider:'pollinations',desc:'Pro-grade Google model'},
 {id:'claude-fast',name:'Claude Haiku 4.5',provider:'pollinations',desc:'Fast Anthropic model'},
 {id:'nova-fast',name:'Amazon Nova Micro',provider:'pollinations',desc:'Cheapest option available'},
 {id:'kimi',name:'Kimi',provider:'pollinations',desc:'Moonshot with reasoning and agentic capabilities'},
 {id:'grok',name:'Grok',provider:'pollinations',desc:'xAI multimodal — fast, non-reasoning'},
 {id:'deepseek',name:'DeepSeek',provider:'pollinations',desc:'Fast reasoning and coding specialist'},
 {id:'aqua:grok',name:'Grok',provider:'aqua',desc:'xAI Grok via Aqua'},
 {id:'aqua:mistral',name:'Mistral',provider:'aqua',desc:'Mistral AI via Aqua'},
 {id:'aqua:qwen',name:'Qwen',provider:'aqua',desc:'Alibaba Qwen via Aqua'},
 {id:'aqua:deepseek-v3',name:'DeepSeek V3',provider:'aqua',desc:'DeepSeek V3 via Aqua'},
 {id:'aqua:gpt-5',name:'GPT-5',provider:'aqua',desc:'OpenAI GPT-5 via Aqua'},
 {id:'aqua:gemini-3',name:'Gemini 3',provider:'aqua',desc:'Google Gemini 3 via Aqua'},
 {id:'aqua:gpt-oss',name:'GPT-OSS',provider:'aqua',desc:'Open-source GPT variant'},
 {id:'aqua:minimax',name:'MiniMax',provider:'aqua',desc:'MiniMax model via Aqua'},
 {id:'aqua:llama-4',name:'Llama 4',provider:'aqua',desc:'Meta Llama 4 via Aqua'},
 {id:'aqua:kimi-k2',name:'Kimi K2',provider:'aqua',desc:'Moonshot Kimi K2 via Aqua'},
 {id:'aqua:step-3.5',name:'Step 3.5',provider:'aqua',desc:'StepFun model via Aqua'},
 {id:'aqua:glm-5',name:'GLM-5',provider:'aqua',desc:'Zhipu GLM-5 via Aqua'},
 {id:'aqua:nemotron',name:'Nemotron',provider:'aqua',desc:'NVIDIA Nemotron via Aqua'},
 {id:'aqua:deepseek-v3.2',name:'DeepSeek V3.2',provider:'aqua',desc:'DeepSeek V3.2 via Aqua'},
 {id:'aqua:haiku-4.5',name:'Haiku 4.5',provider:'aqua',premium:true,desc:'Anthropic Haiku 4.5 — fast + cheap'},
 {id:'aqua:sonnet-4.5',name:'Sonnet 4.5',provider:'aqua',premium:true,desc:'Anthropic Sonnet 4.5 — balanced'},
 {id:'aqua:gpt-5.1',name:'GPT-5.1',provider:'aqua',premium:true,desc:'OpenAI GPT-5.1 — advanced'},
 {id:'aqua:gemini-2.5-pro',name:'Gemini 2.5 Pro',provider:'aqua',premium:true,desc:'Google Gemini 2.5 Pro'},
 {id:'aqua:opus-4.5',name:'Opus 4.5',provider:'aqua',premium:true,desc:'Anthropic Opus 4.5 — top tier'},
 {id:'aqua:gpt-5.4',name:'GPT-5.4',provider:'aqua',premium:true,desc:'OpenAI GPT-5.4 — latest'},
 {id:'aqua:deepseek-v4',name:'DeepSeek V4',provider:'aqua',premium:true,desc:'DeepSeek V4 — advanced reasoning'},
 {id:'aqua:custom',name:'Custom Aqua Model',provider:'aqua',desc:'Type any model ID — requires manual entry'},
];
const VOICES=[
 {id:'alloy',name:'Alloy',desc:'Neutral, balanced'},
 {id:'echo',name:'Echo',desc:'Deep male'},
 {id:'fable',name:'Fable',desc:'British, expressive'},
 {id:'onyx',name:'Onyx',desc:'Deep, authoritative'},
 {id:'nova',name:'Nova',desc:'Warm female'},
 {id:'shimmer',name:'Shimmer',desc:'Clear female'},
 {id:'coral',name:'Coral',desc:'Warm, conversational'},
 {id:'verse',name:'Verse',desc:'Poetic, melodic'},
 {id:'ballad',name:'Ballad',desc:'Musical, singing'},
 {id:'ash',name:'Ash',desc:'Calm, measured'},
 {id:'sage',name:'Sage',desc:'Wise, elder'},
 {id:'amuch',name:'Amuch',desc:'Energetic, youthful'},
 {id:'dan',name:'Dan',desc:'Casual, friendly'},
];
const IMG_MODELS=[
 {id:'flux',name:'Flux',provider:'pollinations',desc:'Fast, high-quality image generation',rec:true},
 {id:'gptimage-large',name:'GPT Image Large',provider:'pollinations',desc:'Large OpenAI image model'},
 {id:'seedream',name:'Seedream',provider:'pollinations',desc:'Seedream image generation'},
 {id:'kontext',name:'Kontext',provider:'pollinations',desc:'Kontext image model'},
 {id:'zimage',name:'ZImage',provider:'pollinations',desc:'ZImage default model'},
 {id:'gptimage',name:'GPT Image',provider:'pollinations',desc:'Standard GPT image model'},
 {id:'seedream5',name:'Seedream 5',provider:'pollinations',desc:'Seedream 5 image model'},
 {id:'aqua:flux-2',name:'Flux 2',provider:'aqua',desc:'Flux 2 via Aqua'},
 {id:'aqua:zimage',name:'ZImage',provider:'aqua',desc:'ZImage via Aqua'},
 {id:'aqua:qwen-image',name:'Qwen Image',provider:'aqua',desc:'Qwen image generation via Aqua'},
 {id:'aqua:nanobanana',name:'NanoBanana',provider:'aqua',desc:'NanoBanana image model via Aqua'},
 {id:'aqua:gptimage-1.5',name:'GPT Image 1.5',provider:'aqua',desc:'GPT Image 1.5 via Aqua'},
 {id:'aqua:gptimage-2',name:'GPT Image 2',provider:'aqua',desc:'GPT Image 2 via Aqua'},
 {id:'aqua:imagen4',name:'Imagen 4',provider:'aqua',desc:'Google Imagen 4 via Aqua'},
 {id:'aqua:seedream',name:'Seedream 5 Lite',provider:'aqua',desc:'Seedream 5 Lite via Aqua'},
 {id:'aqua:midjourney',name:'Midjourney 7',provider:'aqua',desc:'Midjourney 7 via Aqua'},
 {id:'aqua:grok-image',name:'Grok Imagine 1.0',provider:'aqua',desc:'Grok Imagine 1.0 via Aqua'},
];
const TTS_MODELS=[
 {id:'openai-audio',name:'OpenAI Audio',provider:'pollinations',desc:'Voice chat capable — alloy, echo, fable, onyx, nova, shimmer + more',rec:true},
 {id:'openai-audio-large',name:'OpenAI Audio Large',provider:'pollinations',desc:'Premium voice quality'},
 {id:'elevenlabs',name:'ElevenLabs',provider:'pollinations',desc:'Best quality, natural speech — 65 pollen'},
 {id:'elevenmusic',name:'ElevenLabs Music',provider:'pollinations',desc:'Singing and music capable — 4 pollen'},
 {id:'qwen3-tts-flash',name:'Qwen 3 TTS Flash',provider:'pollinations',desc:'Fast Alibaba TTS — 200 pollen'},
 {id:'qwen3-tts-instruct',name:'Qwen 3 TTS Instruct',provider:'pollinations',desc:'Instruct-capable TTS — 500 pollen'},
];
const STT_MODELS=[
 {id:'whisper-large-v3',name:'Whisper Large v3',provider:'pollinations',desc:'Best accuracy — 1000 pollen',rec:true},
 {id:'whisper',name:'Whisper',provider:'pollinations',desc:'Standard Whisper — 1000 pollen'},
 {id:'elevenlabs-scribe-v2',name:'ElevenLabs Scribe v2',provider:'pollinations',desc:'90+ languages, cheaper — 200 pollen'},
 {id:'scribe',name:'Scribe',provider:'pollinations',desc:'ElevenLabs transcription — 200 pollen'},
];

// ===== STATE =====
const ST={
 screen:'dashboard',dashTab:'scenarios',settTab:'providers',
 editCharId:null,editScenId:null,
 charForm:{},scenForm:{},
 settings:{
 pollinationsKey:'pk_LUy70Tu8OwLI1HrU',
 aquaKey:'',customUrl:'',customKey:'',
 charModel:'openai-fast',ctrlModel:'openai',
 imgModel:'flux',ttsModel:'openai-audio',
 sttModel:'whisper-large-v3',
 defVoice:'nova',
 ctrlFreq:10,stWindow:30,streaming:true,
 creativeModel:null,
 creativeImgModel:null,
 customImagePrompt:false,
 },
 rateLimits:{
 pollinations:{calls:[],warned:false},
 aqua:{calls:[],warned:false},
 },
 chat:{
 scenId:null,scenario:null,characters:[],messages:[],rels:{},
 charMems:{},
 activeCharId:null,autoChatRunning:false,autoChatStop:false,
 msgSinceCtrl:0,panelOpen:true,panelTab:'directive',
 directive:{next:'',details:''},debugLog:[],
 sending:false,controllerRunning:false,
 modelsCache:{pollinations:[],aqua:[]},
 sttRecording:false,
 whisper:false,whisperWith:[],
 whisperTarget:null,
 }
};
